export const CONNECT_TO_CHAT = 'CONNECT_TO_CHAT';
export const CONNECT_TO_CHAT_PENDING = 'CONNECT_TO_CHAT_PENDING';
export const CONNECT_TO_CHAT_FULFILLED = 'CONNECT_TO_CHAT_FULFILLED';
export const CONNECT_TO_CHAT_REJECTED = 'CONNECT_TO_CHAT_REJECTED';